import { ApiPromise, WsProvider } from "@polkadot/api";
import { afterAll, describe, expect, expectTypeOf, test } from "vitest";

import { apiTypes } from "../types";

import { LmpApi } from "./lmp";

const provider = new WsProvider("wss://test.chain.polkadex.trade");

const api = new ApiPromise({ provider, ...apiTypes });
const lmp = new LmpApi(api);

describe("lmp queries <> check if markets types are correct", () => {
  afterAll(async () => {
    await api.disconnect();
  });

  test("Get market entries for lmp", async () => {
    const res = await lmp.queryAllMarkets(1);
    expectTypeOf(res).toBeArray();
  });

  test("Eligible rewards for an account for an epoch", async () => {
    const rewards = await lmp.getEligibleRewards(
      4,
      "PDEX-3496813586714279103986568049643838918",
      "esooMNcEcTMzLAzbTA1FKpgurqhzRmLro11MLRyLTJ8bewAq1"
    );
    expectTypeOf(rewards.marketMaking).toBeNumber();
    expectTypeOf(rewards.trading).toBeNumber();
    expectTypeOf(rewards.isClaimed).toBeBoolean();
  });

  test("Query to get accounts for a given market", async () => {
    const res = await lmp.getTopAccounts(
      10,
      "PDEX-3496813586714279103986568049643838918"
    );
    expectTypeOf(res).toBeArray();
  });

  test("Query to get a claimable epoch for an account and market", async () => {
    const res = await lmp.listClaimableEpochs(
      "PDEX-3496813586714279103986568049643838918",
      "esooMNcEcTMzLAzbTA1FKpgurqhzRmLro11MLRyLTJ8bewAq1",
      10
    );
    expectTypeOf(res).toBeArray();
  });

  test("Query fees paid by an account given market and epoch", async () => {
    const res = await lmp.getFeePaidByUserPerEpoch(
      10,
      "PDEX-3496813586714279103986568049643838918",
      "esooMNcEcTMzLAzbTA1FKpgurqhzRmLro11MLRyLTJ8bewAq1"
    );
    expectTypeOf(res).toBeNumber();
  });

  test("Query volume generated by an account given market and epoch", async () => {
    const res = await lmp.getVolumeGeneratedByUserPerEpoch(
      10,
      "PDEX-3496813586714279103986568049643838918",
      "esooMNcEcTMzLAzbTA1FKpgurqhzRmLro11MLRyLTJ8bewAq1"
    );
    expectTypeOf(res).toBeNumber();
  });

  test("get total score and fee for a market in an epoch", async () => {
    const res = await lmp.getTotalScoreAndFeeForMarket(
      25,
      "PDEX-3496813586714279103986568049643838918"
    );
    expectTypeOf(res.score).toBeNumber();
    expectTypeOf(res.totalFee).toBeNumber();
  });

  test("get tradingMetric for account", async () => {
    const res = await lmp.getTraderMetrics(
      25,
      "PDEX-3496813586714279103986568049643838918",
      "esooMNcEcTMzLAzbTA1FKpgurqhzRmLro11MLRyLTJ8bewAq1"
    );
    // check if types are correct
    expectTypeOf(res.mmScore).toBeNumber();
    expectTypeOf(res.tradingScore).toBeNumber();
  });

  test("create extrinsic for claim rewards", async () => {
    const res = await lmp.claimRewardsTx(
      25,
      "PDEX-3496813586714279103986568049643838918"
    );
    expectTypeOf(res).toBeObject();
  });
});
