name: CI Build and Test

on:
  pull_request:
    types: [labeled, synchronize]
  push:
    branches: [main]

jobs:
  build:
    if: |
      contains(github.event.pull_request.labels.*.name, 'A0-PleaseReview') ||
      contains(github.event_name, 'push')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup Yarn
        run : npm install -g yarn && yarn cache clean && yarn install

      - name: Build Packages
        run : yarn build

      - name: Lint Packages
        run : yarn lint

  all:
    # This job ensures that all jobs above (now we have just build) are successful.
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - run: echo Completed
