name: CI Tests And Build

on:
  pull_request:
    types: [labeled]
  push:
    branches: [main]

jobs:
  build:
    if: |
      contains(github.event.pull_request.labels.*.name, 'A0-PleaseReview') ||
      contains(github.event_name, 'push')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 19.x, 20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn build
      - run: yarn lint
      - run: yarn test

  all:
    # This job ensures that all jobs above (now we have just build) are successful.
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - run: echo Completed
